/**
 * Use case dependency injection tokens
 * Used for identifying use case implementations at runtime
 */
export const USE_CASE_TOKENS = {
  // Auth use cases
  RegisterUserUseCase: Symbol.for('RegisterUserUseCase'),
  VerifyOtpUseCase: Symbol.for('VerifyOtpUseCase'),
  ResendOtpUseCase: Symbol.for('ResendOtpUseCase'),
  LoginUserUseCase: Symbol.for('LoginUserUseCase'),
  RefreshTokenUseCase: Symbol.for('RefreshTokenUseCase'),
  LogoutUserUseCase: Symbol.for('LogoutUserUseCase'),
  ForgotPasswordUseCase: Symbol.for('ForgotPasswordUseCase'),
  ResetPasswordUseCase: Symbol.for('ResetPasswordUseCase'),
  GoogleAuthUseCase: Symbol.for('GoogleAuthUseCase'),
  SetupPasswordUseCase: Symbol.for('SetupPasswordUseCase'),
  LinkGoogleAccountUseCase: Symbol.for('LinkGoogleAccountUseCase'),
  // User use cases
  GetUserProfileUseCase: Symbol.for('GetUserProfileUseCase'),
  UpdateUserProfileUseCase: Symbol.for('UpdateUserProfileUseCase'),
  GenerateUploadUrlUseCase: Symbol.for('GenerateUploadUrlUseCase'),
  ChangePasswordUseCase: Symbol.for('ChangePasswordUseCase'),
  GetUserByIdUseCase: Symbol.for('GetUserByIdUseCase'),
  ListUsersUseCase: Symbol.for('ListUsersUseCase'),
  ChangeUserStatusUseCase: Symbol.for('ChangeUserStatusUseCase'),
  ChangeUserRoleUseCase: Symbol.for('ChangeUserRoleUseCase'),
  GetUserStatisticsUseCase: Symbol.for('GetUserStatisticsUseCase'),
  DeleteUserAccountUseCase: Symbol.for('DeleteUserAccountUseCase'),
  // Driver use cases
  CreateDriverUseCase: Symbol.for('CreateDriverUseCase'),
  ListDriversUseCase: Symbol.for('ListDriversUseCase'),
  GetDriverByIdUseCase: Symbol.for('GetDriverByIdUseCase'),
  UpdateDriverUseCase: Symbol.for('UpdateDriverUseCase'),
  UpdateDriverStatusUseCase: Symbol.for('UpdateDriverStatusUseCase'),
  DeleteDriverUseCase: Symbol.for('DeleteDriverUseCase'),
  LoginDriverUseCase: Symbol.for('LoginDriverUseCase'),
  ChangeDriverPasswordUseCase: Symbol.for('ChangeDriverPasswordUseCase'),
  UpdateProfilePictureUseCase: Symbol.for('UpdateProfilePictureUseCase'),
  UpdateLicenseCardPhotoUseCase: Symbol.for('UpdateLicenseCardPhotoUseCase'),
  UpdateOnboardingPasswordUseCase: Symbol.for('UpdateOnboardingPasswordUseCase'),
  GetDriverProfileUseCase: Symbol.for('GetDriverProfileUseCase'),
  GetDriverStatisticsUseCase: Symbol.for('GetDriverStatisticsUseCase'),
  CompleteDriverOnboardingUseCase: Symbol.for('CompleteDriverOnboardingUseCase'),
  GetDriverInfoUseCase: Symbol.for('GetDriverInfoUseCase'),
  // Vehicle Type use cases
  CreateVehicleTypeUseCase: Symbol.for('CreateVehicleTypeUseCase'),
  GetVehicleTypeUseCase: Symbol.for('GetVehicleTypeUseCase'),
  GetAllVehicleTypesUseCase: Symbol.for('GetAllVehicleTypesUseCase'),
  UpdateVehicleTypeUseCase: Symbol.for('UpdateVehicleTypeUseCase'),
  DeleteVehicleTypeUseCase: Symbol.for('DeleteVehicleTypeUseCase'),
  // Vehicle use cases
  CreateVehicleUseCase: Symbol.for('CreateVehicleUseCase'),
  GetVehicleUseCase: Symbol.for('GetVehicleUseCase'),
  GetAllVehiclesUseCase: Symbol.for('GetAllVehiclesUseCase'),
  GetVehiclesByTypeUseCase: Symbol.for('GetVehiclesByTypeUseCase'),
  UpdateVehicleUseCase: Symbol.for('UpdateVehicleUseCase'),
  UpdateVehicleStatusUseCase: Symbol.for('UpdateVehicleStatusUseCase'),
  DeleteVehicleUseCase: Symbol.for('DeleteVehicleUseCase'),
  GetVehicleFilterOptionsUseCase: Symbol.for('GetVehicleFilterOptionsUseCase'),
  GenerateVehicleImageUploadUrlUseCase: Symbol.for('GenerateVehicleImageUploadUrlUseCase'),
  DeleteVehicleImagesUseCase: Symbol.for('DeleteVehicleImagesUseCase'),
  // Amenity use cases
  CreateAmenityUseCase: Symbol.for('CreateAmenityUseCase'),
  GetAmenityUseCase: Symbol.for('GetAmenityUseCase'),
  GetAllAmenitiesUseCase: Symbol.for('GetAllAmenitiesUseCase'),
  GetPaidAmenitiesUseCase: Symbol.for('GetPaidAmenitiesUseCase'),
  UpdateAmenityUseCase: Symbol.for('UpdateAmenityUseCase'),
  DeleteAmenityUseCase: Symbol.for('DeleteAmenityUseCase'),
  // Quote use cases
  CreateQuoteDraftUseCase: Symbol.for('CreateQuoteDraftUseCase'),
  UpdateQuoteDraftUseCase: Symbol.for('UpdateQuoteDraftUseCase'),
  GetQuoteUseCase: Symbol.for('GetQuoteUseCase'),
  GetQuotesListUseCase: Symbol.for('GetQuotesListUseCase'),
  DeleteQuoteUseCase: Symbol.for('DeleteQuoteUseCase'),
  CalculateRoutesUseCase: Symbol.for('CalculateRoutesUseCase'),
  GetVehicleRecommendationsUseCase: Symbol.for('GetVehicleRecommendationsUseCase'),
  CalculateQuotePricingUseCase: Symbol.for('CalculateQuotePricingUseCase'),
  SubmitQuoteUseCase: Symbol.for('SubmitQuoteUseCase'),
  // Event Type use cases
  GetEventTypesUseCase: Symbol.for('GetEventTypesUseCase'),
  CreateCustomEventTypeUseCase: Symbol.for('CreateCustomEventTypeUseCase'),
  // Admin Quote use cases
  GetAdminQuotesListUseCase: Symbol.for('GetAdminQuotesListUseCase'),
  GetAdminQuoteUseCase: Symbol.for('GetAdminQuoteUseCase'),
  UpdateQuoteStatusUseCase: Symbol.for('UpdateQuoteStatusUseCase'),
  AssignDriverToQuoteUseCase: Symbol.for('AssignDriverToQuoteUseCase'),
  RecalculateQuoteUseCase: Symbol.for('RecalculateQuoteUseCase'),
  // Pricing Config use cases
  GetPricingConfigUseCase: Symbol.for('GetPricingConfigUseCase'),
  CreatePricingConfigUseCase: Symbol.for('CreatePricingConfigUseCase'),
  GetPricingConfigHistoryUseCase: Symbol.for('GetPricingConfigHistoryUseCase'),
  ActivatePricingConfigUseCase: Symbol.for('ActivatePricingConfigUseCase'),
  // Chat use cases
  CreateChatUseCase: Symbol.for('CreateChatUseCase'),
  GetUserChatsUseCase: Symbol.for('GetUserChatsUseCase'),
  GetChatByContextUseCase: Symbol.for('GetChatByContextUseCase'),
  // Message use cases
  SendMessageUseCase: Symbol.for('SendMessageUseCase'),
  GetChatMessagesUseCase: Symbol.for('GetChatMessagesUseCase'),
  MarkMessageAsReadUseCase: Symbol.for('MarkMessageAsReadUseCase'),
  GetUnreadMessageCountUseCase: Symbol.for('GetUnreadMessageCountUseCase'),
  GetTotalUnreadMessageCountUseCase: Symbol.for('GetTotalUnreadMessageCountUseCase'),
  // Notification use cases
  CreateNotificationUseCase: Symbol.for('CreateNotificationUseCase'),
  GetUserNotificationsUseCase: Symbol.for('GetUserNotificationsUseCase'),
  MarkNotificationAsReadUseCase: Symbol.for('MarkNotificationAsReadUseCase'),
  MarkAllNotificationsAsReadUseCase: Symbol.for('MarkAllNotificationsAsReadUseCase'),
  GetUnreadNotificationCountUseCase: Symbol.for('GetUnreadNotificationCountUseCase'),
  MarkChatNotificationsAsReadUseCase: Symbol.for('MarkChatNotificationsAsReadUseCase'),
  // Payment use cases
  CreatePaymentIntentUseCase: Symbol.for('CreatePaymentIntentUseCase'),
  HandlePaymentWebhookUseCase: Symbol.for('HandlePaymentWebhookUseCase'),
  // Reservation use cases
  CreateReservationUseCase: Symbol.for('CreateReservationUseCase'),
  GetReservationUseCase: Symbol.for('GetReservationUseCase'),
  GetReservationsListUseCase: Symbol.for('GetReservationsListUseCase'),
  // Admin Reservation use cases
  GetAdminReservationsListUseCase: Symbol.for('GetAdminReservationsListUseCase'),
  GetAdminReservationUseCase: Symbol.for('GetAdminReservationUseCase'),
  UpdateReservationStatusUseCase: Symbol.for('UpdateReservationStatusUseCase'),
  AddPassengersToReservationUseCase: Symbol.for('AddPassengersToReservationUseCase'),
  ChangeReservationDriverUseCase: Symbol.for('ChangeReservationDriverUseCase'),
  AdjustReservationVehiclesUseCase: Symbol.for('AdjustReservationVehiclesUseCase'),
  UpdateReservationItineraryUseCase: Symbol.for('UpdateReservationItineraryUseCase'),
  ProcessReservationRefundUseCase: Symbol.for('ProcessReservationRefundUseCase'),
  CancelReservationUseCase: Symbol.for('CancelReservationUseCase'),
  AddReservationChargeUseCase: Symbol.for('AddReservationChargeUseCase'),
  MarkChargeAsPaidUseCase: Symbol.for('MarkChargeAsPaidUseCase'),
  ExportReservationPDFUseCase: Symbol.for('ExportReservationPDFUseCase'),
  ExportReservationCSVUseCase: Symbol.for('ExportReservationCSVUseCase'),
  CreateChargePaymentIntentUseCase: Symbol.for('CreateChargePaymentIntentUseCase'),
  // Dashboard use cases
  GetDashboardStatsUseCase: Symbol.for('GetDashboardStatsUseCase'),
  GetRecentActivityUseCase: Symbol.for('GetRecentActivityUseCase'),
} as const;

