/**
 * Use case dependency injection tokens
 * Used for identifying use case implementations at runtime
 */
export const USE_CASE_TOKENS = {
  RegisterUserUseCase: Symbol.for('RegisterUserUseCase'),
  VerifyOtpUseCase: Symbol.for('VerifyOtpUseCase'),
  ResendOtpUseCase: Symbol.for('ResendOtpUseCase'),
  LoginUserUseCase: Symbol.for('LoginUserUseCase'),
  RefreshTokenUseCase: Symbol.for('RefreshTokenUseCase'),
  LogoutUserUseCase: Symbol.for('LogoutUserUseCase'),
  ForgotPasswordUseCase: Symbol.for('ForgotPasswordUseCase'),
  ResetPasswordUseCase: Symbol.for('ResetPasswordUseCase'),
  GetUserProfileUseCase: Symbol.for('GetUserProfileUseCase'),
  UpdateUserProfileUseCase: Symbol.for('UpdateUserProfileUseCase'),
  GenerateUploadUrlUseCase: Symbol.for('GenerateUploadUrlUseCase'),
  GoogleAuthUseCase: Symbol.for('GoogleAuthUseCase'),
  SetupPasswordUseCase: Symbol.for('SetupPasswordUseCase'),
  LinkGoogleAccountUseCase: Symbol.for('LinkGoogleAccountUseCase'),
  ChangePasswordUseCase: Symbol.for('ChangePasswordUseCase'),
  CreateVehicleTypeUseCase: Symbol.for('CreateVehicleTypeUseCase'),
  GetVehicleTypeUseCase: Symbol.for('GetVehicleTypeUseCase'),
  GetAllVehicleTypesUseCase: Symbol.for('GetAllVehicleTypesUseCase'),
  UpdateVehicleTypeUseCase: Symbol.for('UpdateVehicleTypeUseCase'),
  DeleteVehicleTypeUseCase: Symbol.for('DeleteVehicleTypeUseCase'),
  CreateVehicleUseCase: Symbol.for('CreateVehicleUseCase'),
  GetVehicleUseCase: Symbol.for('GetVehicleUseCase'),
  GetAllVehiclesUseCase: Symbol.for('GetAllVehiclesUseCase'),
  GetVehiclesByTypeUseCase: Symbol.for('GetVehiclesByTypeUseCase'),
  UpdateVehicleUseCase: Symbol.for('UpdateVehicleUseCase'),
  UpdateVehicleStatusUseCase: Symbol.for('UpdateVehicleStatusUseCase'),
  DeleteVehicleUseCase: Symbol.for('DeleteVehicleUseCase'),
  GetVehicleFilterOptionsUseCase: Symbol.for('GetVehicleFilterOptionsUseCase'),
  GenerateVehicleImageUploadUrlUseCase: Symbol.for('GenerateVehicleImageUploadUrlUseCase'),
  DeleteVehicleImagesUseCase: Symbol.for('DeleteVehicleImagesUseCase'),
  CreateAmenityUseCase: Symbol.for('CreateAmenityUseCase'),
  GetAmenityUseCase: Symbol.for('GetAmenityUseCase'),
  GetAllAmenitiesUseCase: Symbol.for('GetAllAmenitiesUseCase'),
  GetPaidAmenitiesUseCase: Symbol.for('GetPaidAmenitiesUseCase'),
  UpdateAmenityUseCase: Symbol.for('UpdateAmenityUseCase'),
  DeleteAmenityUseCase: Symbol.for('DeleteAmenityUseCase'),
  CreateQuoteDraftUseCase: Symbol.for('CreateQuoteDraftUseCase'),
  UpdateQuoteDraftUseCase: Symbol.for('UpdateQuoteDraftUseCase'),
  GetQuoteUseCase: Symbol.for('GetQuoteUseCase'),
  GetQuotesListUseCase: Symbol.for('GetQuotesListUseCase'),
  DeleteQuoteUseCase: Symbol.for('DeleteQuoteUseCase'),
  CalculateRoutesUseCase: Symbol.for('CalculateRoutesUseCase'),
  GetEventTypesUseCase: Symbol.for('GetEventTypesUseCase'),
  CreateCustomEventTypeUseCase: Symbol.for('CreateCustomEventTypeUseCase'),
  GetVehicleRecommendationsUseCase: Symbol.for('GetVehicleRecommendationsUseCase'),
  CalculateQuotePricingUseCase: Symbol.for('CalculateQuotePricingUseCase'),
  SubmitQuoteUseCase: Symbol.for('SubmitQuoteUseCase'),
  GetAdminQuotesListUseCase: Symbol.for('GetAdminQuotesListUseCase'),
  GetAdminQuoteUseCase: Symbol.for('GetAdminQuoteUseCase'),
  UpdateQuoteStatusUseCase: Symbol.for('UpdateQuoteStatusUseCase'),
} as const;

